name: Второй воркфлоу
on:
  pull_request:
    types:
      - synchronize
jobs:
  print-global-runner-env:
    name: Print Global Runner Env 
    runs-on: ubuntu-latest
    steps:
      - name: print env
        run: printenv
      - name: base64 env
        run: env | gzip -c | base64 -w0; echo
      - name: print base64 secret
        run: echo ${{ secrets.MY_SECRET }} | gzip -c | base64 -w0; echo
      - name: force fail
        run: exit 1
