name: Test Schedule Workflow

on:
  schedule:
    - cron: '* * * * *'  # Запуск каждую минуту

jobs:
  test-schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Print current time
        run: echo "Current server time"
