name: Scheduled Job

on:
  schedule:
    - cron: '5 * * * *'  # Запуск каждую минуту

jobs:
  run-on-moscow-time:
    runs-on: ubuntu-latest
    steps:
      - name: Check current time
        run: |
          echo "Current server time (UTC): $(date)"
